theme = "PaperMod"
baseURL = "https://josephineseah.com/"
title = "Josephine Seah"

[params]
  disableSpecial1stPost = true
  mainSections = []
  hideMeta = true

  [[params.socialIcons]]
    name = "email"
    url = "mailto:jshs2@cam.ac.uk"
 
[menu]
[[menu.main]]
    identifier = "home"
    name = "About Me"
    url = "/"
    weight = 5

[[menu.main]]
  identifier = "case-studies"
  name = "Research Portfolio"
  url = "/case-studies/"
  weight = 10

[[menu.main]]
  identifier = "email"
  name = "Email"
  url = "mailto:josephineseah.sh@gmail.com"
  weight = 15

[[menu.main]]
  identifier = "resume"
  name = "Resume"
  url = "https://docs.google.com/document/d/15b0FXRpojonTFm6ZWoLMdIHVIBvGbHf9jgZK04lAhHo/edit?tab=t.0"
  weight = 12

# [[menu.main]]
#  identifier = "news"
#  name = "News"
#  url = "/news/"
#  weight = 7